<title>Imprint · Henning Witzel</title>
</head>
  <body basepath='###basepath###'></body>
  <div id='clearbutton'></div>
</html>
<div class='image' data_image_1280='###basepath###img/header/###page###-header-1280.jpg' data_image_1440='###basepath###img/header/###page###-header-1440.jpg' data_image_1920='###basepath###img/header/###page###-header-1920.jpg' data_image_800='###basepath###img/header/###page###-header-800.jpg' id='header'></div>
<div class='text' id='background'>
  <div id='wrapper'>
    <div id='logo'>
      <a href='###basepath###'>
        <div id='link'></div>
      </a>
    </div>
     ###menu###
    <div class='content'>
      <div class='video'>
        <h1>Imprint</h1>
        <h2>Angaben gemäß §5 TMG</h2>
        <p>Henning Witzel <br />Rudolf-Schwarz-Str. 6<br />10407 Berlin</p>        
        <p><a href="mailto:witzel@hey.com?Subject=Hello%20Henning">witzel@hey.com</a> <br /> <a href='http://www.henning-witzel.de'>www.henning-witzel.de</a></p>
        <p>Inhaltlich Verantwortlicher gem. § 55 II RStV: Henning Witzel (Anschrift s.o.)</p>
        <br /><br />
        <h2>Haftung für Inhalte</h2>
      <p>Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>
      <br>
      <h2>Haftung für Links</h2>
      <p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>
      <br>
      <h2>Urheberrecht</h2>
      <p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>
      <br>
      <h2>Datenschutz</h2>
      <p>Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.<br />Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.<br /><br />Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.</p>
      <br>
      <h2>Google Analytics</h2>
      <p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. ("Google") Google Analytics verwendet sog. "Cookies", Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglicht. Die durch den Cookie erzeugten Informationen über Ihre Benutzung diese Website (einschließlich Ihrer IP-Adresse) wird an einen Server von Google in den USA übertragen und dort gespeichert. Google wird diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google in Verbindung bringen. Sie können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.<br /><br />Die auf diesen Seiten verwendete Version von Google Analytics verzichtet auf die Weitergabe der vollständigen IP-Adresse. Somit bleibt ihr Nutzerprofil anonym. Sollten sie Google Analytics vollständig deaktivieren wollen, können Sie dies, indem Sie das kostenlose Add-on Opt-Out der Firma Google für Ihren aktuellen Webbrowser installieren. Das Add-on teilt dem JavaScript (ga.js) von Google Analytics mit, dass keine Informationen über den Website-Besuch an Google Analytics übermittelt werden sollen. Falls Sie diese Funktion nutzen möchten, laden Sie das Add-on herunter und installieren Sie es für Ihren aktuellen Webbrowser.</p>
      <br>
      <h2>Nutzungsbedingungen für unsere Facebook-Fanpage</h2>
      <p><b>§ 1 Geltungsbereich dieses Disclaimers</b><br/><br/>Für die Nutzung dieser Facebook-Fanpage gelten zwischen dem Nutzer und dem Betreiber der Fanpage (nachfolgend "Anbieter" genannt) die folgenden Nutzungsbedingungen.<br/><br/>Die Nutzung ist nur zulässig, wenn Sie als Nutzer diese Nutzungsbedingungen akzeptieren.</p>
      <p><br/><br/><b>§ 2 Haftungshinweise zu Inhalten auf unserer Facebook-Fanpage</b><br/><br/>Die Inhalte dieser Facebook-Fanpage werden mit größtmöglicher Sorgfalt erstellt. Der Anbieter übernimmt jedoch keine Gewähr für die Richtigkeit, Vollständigkeit und Aktualität der bereitgestellten Inhalte. Die Nutzung der Inhalte der Facebook-Fanpage erfolgt auf eigene Gefahr des Nutzers. Namentlich gekennzeichnete Beiträge geben die Meinung des jeweiligen Autors und nicht immer die Meinung des Anbieters wieder.</p>
      <p><br/><br/><b>§ 3 Externe Links auf unserer Facebook-Fanpage</b><br/><br/>Diese Facebook-Fanpage enthält Verknüpfungen zu Websites Dritter ("externe Links"). Diese Websites unterliegen der Haftung der jeweiligen Betreiber. Der Anbieter hat bei der erstmaligen Verknüpfung der externen Links die fremden Inhalte daraufhin überprüft, ob etwaige Rechtsverstöße bestehen. Zu dem Zeitpunkt waren keine Rechtsverstöße ersichtlich. Der Anbieter hat keinerlei Einfluss auf die aktuelle und zukünftige Gestaltung und auf die Inhalte der verknüpften Seiten. Das Setzen von externen Links bedeutet nicht, dass sich der Anbieter die hinter dem Verweis oder Link liegenden Inhalte zu eigen macht. Eine ständige Kontrolle der externen Links ist für den Anbieter ohne konkrete Hinweise auf Rechtsverstöße nicht zumutbar. Bei Kenntnis von Rechtsverstößen werden jedoch derartige externe Links unverzüglich gelöscht.</p>
      <p><br/><br/><b>§ 4 Pflichten als Nutzer unserer Facebook-Fanpage</b><br/><br/>(1) Als Nutzer verpflichten Sie sich, dass Sie keine Beiträge / Kommentare auf unserer Facebook-Fanpage veröffentlichen werden, die gegen diese Regeln, die guten Sitten oder sonst gegen geltendes deutsches Recht verstoßen. Es ist Ihnen insbesondere untersagt,<br/><br/>beleidigende oder unwahre Inhalte zu veröffentlichen;<br/><br/>gesetzlich, insbesondere durch das Urheber- und Markenrecht, geschützte Inhalte ohne Berechtigung zu verwenden;<br/><br/>wettbewerbswidrige Handlungen vorzunehmen;<br/><br/>Werbung auf der Facebook-Fanpage ohne ausdrückliche schriftliche Genehmigung durch den Anbieter zu betreiben. Dies gilt auch für sog. Schleichwerbung wie insbesondere das Verlinken der eigenen Fanpage oder Webseite mit oder ohne Beitext in Kommentaren oder innerhalb von Beiträgen.<br/><br/>(2) Der Anbieter hat das Recht, Beiträge und Kommentare zu löschen, wenn diese einen Rechtsverstoß enthalten könnten.<br/><br/>(3) Als Nutzer verpflichten Sie sich, vor der Veröffentlichung Ihrer Beiträge und Kommentare diese daraufhin zu überprüfen, ob diese Angaben enthalten, die Sie nicht veröffentlichen möchten. Ihre Beiträge und Themen können in Suchmaschinen erfasst und damit weltweit zugreifbar werden. Ein Anspruch auf Löschung oder Korrektur solcher Suchmaschineneinträge gegenüber dem Anbieter ist ausgeschlossen.<br/><br/>(4) Sollten Dritte oder andere Nutzer den Anbieter wegen möglicher Rechtsverstöße in Anspruch nehmen, die a) aus den von Ihnen als Nutzer eingestellten Inhalten auf der Facebook-Fanpage resultieren und/oder b) aus der Nutzung der Fanpage des Anbieters durch Sie als Nutzer entstehen, verpflichten Sie sich als Nutzer, den Anbieter von jeglichen Ansprüchen, einschließlich Schadensersatzansprüchen, freizustellen und dem Anbieter die Kosten zu ersetzen, die diesem wegen der möglichen Rechtsverletzung entstehen. Der Anbieter wird insbesondere von den Kosten der notwendigen Rechtsverteidigung freigestellt. Der Anbieter ist berechtigt, hierfür von Ihnen als Nutzer einen angemessenen Vorschuss zu fordern. Als Nutzer sind Sie verpflichtet, den Anbieter nach Treu und Glauben mit Informationen und Unterlagen bei der Rechtsverteidigung gegenüber Dritten zu unterstützen. Alle weitergehenden Rechte sowie Schadensersatzansprüche des Anbieters bleiben unberührt. Wenn Sie als Nutzer die mögliche Rechtsverletzung nicht zu vertreten haben, bestehen die zuvor genannten Pflichten nicht.</p>
      <p><br/><br/><b>§ 5 Urheber- und Leistungsschutzrechte</b><br/><br/>(1) Die auf dieser Facebook-Fanpage veröffentlichten Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Jede vom deutschen Urheber- und Leistungsschutzrecht nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des Anbieters oder jeweiligen Rechteinhabers. Dies gilt insbesondere für Vervielfältigung, Bearbeitung, Übersetzung, Einspeicherung, Verarbeitung bzw. Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. Inhalte und Rechte Dritter sind dabei als solche gekennzeichnet. Die unerlaubte Vervielfältigung oder Weitergabe einzelner Inhalte oder kompletter Seiten ist nicht gestattet und strafbar. Lediglich die Herstellung von Kopien und Downloads für den persönlichen, privaten und nicht kommerziellen Gebrauch ist erlaubt.<br/><br/>(2) Die Darstellung dieser Website in fremden Frames ist nur mit schriftlicher Erlaubnis zulässig.</p>
      <p><br/><br/><b>§ 6 Datenschutz auf Facebook / beim „Gefällt mir“-Button</b><br/><br/>(1) Der Anbieter dieser Facebook-Fanpage nutzt Plugins des Anbieters Facebook.com, welche durch das Unternehmen Facebook Inc., 1601 S. California Avenue, Palo Alto, CA 94304 in den USA bereitgestellt werden. Nutzer unserer Webseite, auf der das Facebook-Plugin installiert ist, werden hiermit darauf hingewiesen, dass durch das Plugin eine Verbindung zu Facebook aufgebaut wird, wodurch eine Übermittlung an Ihren Browser durchgeführt wird, damit das Plugin auf der Webseite erscheint.<br/><br/>(2) Des Weiteren werden durch die Nutzung Daten an die Facebook-Server weitergeleitet, welche Informationen über Ihre Webseitenbesuche auf unserer Homepage enthalten. Dies hat für eingeloggte Facebook-Nutzer zur Folge, dass die Nutzungsdaten ihrem persönlichen Facebook-Account zugeordnet werden. Sobald Sie als eingeloggter Facebook-Nutzer aktiv das Facebook-Plugin nutzen (z.B. durch das Klicken auf den „Gefällt mir“ Knopf oder die Nutzung der Kommentarfunktion), werden diese Daten zu Ihrem Facebook-Account übertragen und veröffentlicht. Dies können Sie nur durch vorheriges Ausloggen aus Ihrem Facebook-Account umgehen.<br/><br/>(3) Es ist uns nicht genau bekannt, welche Daten Facebook speichert und nutzt. Sie müssen als Nutzer der Fanpage daher damit rechnen, dass Facebook auch Ihre Aktionen auf der Fanpage lückenlos speichert.<br/><br/>(4) Facebook erhält durch den Klick auf den „Gefällt mir“ – Button Ihre IP-Adresse, Prozessortyp und Browserversion. Über Ihre IP-Adresse könnte Facebook zusammen mit anderen Daten sowie Ihrem Realnamen, wenn Sie diesen bei Ihrem Facebook-Profil angegeben haben, Ihre Identität und Gewohnheiten unter diesem Profil ermitteln. Wenn Sie sich immer über dieses Nutzerprofil bei Facebook einloggen, könnte Facebook insbesondere Ihre Vorlieben, Kontakte und Lebensweise herausfinden.</p>
      <p><br/><br/><b>§ 7 Sonstige Regelungen</b><br/><br/>(1) Im Übrigen gelten die Allgemeinen Nutzungsbedingungen der Facebook Ireland Limited, Hanover Reach, 5-7 Hanover Quay, Dublin 2, Ireland unter https://www.facebook.com/terms.php<br/><br/>(2) Hinsichtlich des Datenschutzes auf Facebook beachten Sie bitte die folgenden Datenschutzhinweise der Facebook Ireland Limited: https://www.facebook.com/about/privacy/</p>
      
      <p><h2>Datenschutzerklärung</h2></p><p><strong>Geltungsbereich</strong></p><p>Diese Datenschutzerklärung klärt Nutzer über die Art, den Umfang und Zwecke der Erhebung und Verwendung personenbezogener Daten durch den verantwortlichen Anbieter, wie oben gennant, auf dieser Website (im folgenden “Angebot”) auf.<br />
<br />
Die rechtlichen Grundlagen des Datenschutzes finden sich im Bundesdatenschutzgesetz (BDSG) und dem Telemediengesetz (TMG).<br />
<br />
</p><p><h2>Zugriffsdaten/ Server-Logfiles</h2></p><p><span class="sd-muster-content">Der Anbieter (beziehungsweise sein Webspace-Provider) erhebt Daten über jeden Zugriff auf das Angebot (so genannte Serverlogfiles). Zu den Zugriffsdaten gehören:<br />
<br />
Name der abgerufenen Webseite, Datei, Datum und Uhrzeit des Abrufs, übertragene Datenmenge, Meldung über erfolgreichen Abruf, Browsertyp nebst Version, das Betriebssystem des Nutzers, Referrer URL (die zuvor besuchte Seite), IP-Adresse und der anfragende Provider.<br />
<br />
Der Anbieter verwendet die Protokolldaten nur für statistische Auswertungen zum Zweck des Betriebs, der Sicherheit und der Optimierung des Angebotes. Der Anbieterbehält sich jedoch vor, die Protokolldaten nachträglich zu überprüfen, wenn aufgrund konkreter Anhaltspunkte der berechtigte Verdacht einer rechtswidrigen Nutzung besteht.</span></p><p><h2>Kontaktaufnahme</h2></p><p><span class="sd-muster-content">Bei der Kontaktaufnahme mit dem Anbieter (zum Beispiel per Kontaktformular oder E-Mail) werden die Angaben des Nutzers zwecks Bearbeitung der Anfrage sowie für den Fall, dass Anschlussfragen entstehen, gespeichert.</span></p><p><h2>Einbindung von Diensten und Inhalten Dritter</h2></p><p><span class="sd-muster-content">Es kann vorkommen, dass innerhalb dieses Onlineangebotes Inhalte Dritter, wie zum Beispiel Videos von YouTube, Kartenmaterial von Google-Maps, RSS-Feeds oder Grafiken von anderen Webseiten eingebunden werden. Dies setzt immer voraus, dass die Anbieter dieser Inhalte (nachfolgend bezeichnet als "Dritt-Anbieter") die IP-Adresse der Nutzer wahr nehmen. Denn ohne die IP-Adresse, könnten sie die Inhalte nicht an den Browser des jeweiligen Nutzers senden. Die IP-Adresse ist damit für die Darstellung dieser Inhalte erforderlich. Wir bemühen uns nur solche Inhalte zu verwenden, deren jeweilige Anbieter die IP-Adresse lediglich zur Auslieferung der Inhalte verwenden. Jedoch  haben wir keinen Einfluss darauf, falls die Dritt-Anbieter die IP-Adresse z.B. für statistische Zwecke speichern. Soweit dies uns bekannt ist, klären wir die Nutzer darüber auf.<br />
</span></p><p><h2>Cookies</h2></p><p><span class="sd-muster-content">Cookies sind kleine Dateien, die es ermöglichen, auf dem Zugriffsgerät der Nutzer (PC, Smartphone o.ä.) spezifische, auf das Gerät bezogene Informationen zu speichern. Sie dienen zum einem der Benutzerfreundlichkeit von Webseiten und damit den Nutzern (z.B. Speicherung von Logindaten). Zum anderen dienen sie, um die statistische Daten der Webseitennutzung zu erfassen und sie zwecks Verbesserung des Angebotes analysieren zu können. Die Nutzer können auf den Einsatz der Cookies Einfluss nehmen. Die meisten Browser verfügen eine Option mit der das Speichern von Cookies eingeschränkt oder komplett verhindert wird. Allerdings wird darauf hingewiesen, dass die Nutzung und insbesondere der Nutzungskomfort ohne Cookies eingeschränkt werden.<br />
<br />
Sie können viele Online-Anzeigen-Cookies von Unternehmen über die US-amerikanische  Seite <a href="http://www.aboutads.info/choices/" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://www.aboutads.info/choices/']);">http://www.aboutads.info/choices/</a> oder die EU-Seite <a href="http://www.youronlinechoices.com/uk/your-ad-choices/ " onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://www.youronlinechoices.com/uk/your-ad-choices/']);">http://www.youronlinechoices.com/uk/your-ad-choices/ </a> verwalten.</span></p><p><h2>Google Analytics</h2></p><p><span class="sd-muster-content">Dieses Angebot benutzt Google Analytics, einen Webanalysedienst der Google Inc. („Google“). Google Analytics verwendet sog. „Cookies“, Textdateien, die auf Computer der Nutzer gespeichert werden und die eine Analyse der Benutzung der Website durch sie ermöglichen. Die durch den Cookie erzeugten Informationen über Benutzung dieser Website durch die Nutzer werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert.<br />
<br />
Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite, wird die IP-Adresse der Nutzer von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Die IP-Anonymisierung ist auf dieser Website aktiv. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um die Nutzung der Website durch die Nutzer auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen.<br />
<br />
Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Die Nutzer können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; Dieses Angebot weist die Nutzer jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Die Nutzer können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: http://tools.google.com/dlpage/gaoptout?hl=de.<br />
</span></p><p><h2>Widerruf, Änderungen, Berichtigungen und Aktualisierungen</h2></p><p>Der Nutzer hat das Recht, auf Antrag unentgeltlich Auskunft zu erhalten über die personenbezogenen Daten, die über ihn gespeichert wurden. Zusätzlich hat der Nutzer das Recht auf Berichtigung unrichtiger Daten, Sperrung und Löschung seiner personenbezogenen Daten, soweit dem keine gesetzliche Aufbewahrungspflicht entgegensteht.<br />
</p>   </div>
    </div>
    <div class='clearfix'></div>
  </div>
</div>
